### ISSUE TITLE
ttuksa's work on the library

### ISSUE THREAD

**Issue by wmarkow** [andykarpov/PT2314#1]
@andykarpov, @ttuksa, thanks for your effort for putting the library into the life.

@ttuksa, you made some useful improvements in the library. I think it would be good if your changes were merged into the main line of anykarpov's. You introduced a **gain** method and added some examples. That's a good change. I suggest that you make a pull request.

**Comment by andykarpov** [comment]
Yes, please! @ttuksa, please make a pull request - i'll merge it into my library then!
@wmarkow, thanks for suggestions!

**Comment by kimiastrid** [comment]
Hi! :D Sorry it took me so long to respond! I'm not a very active member of Github, just an amateur programmer. I'm glad that you like my changes. I created a pull request (that would be my first, I hope I did everything right). Great library, though!

**Comment by wmarkow** [comment]
I see that pull request #6 has been merged. I'm closing this issue.
