### ISSUE TITLE
PT2314 seems to work with 5V power supply

### ISSUE THREAD

**Issue by wmarkow** [andykarpov/PT2314#2]
I started to use PT2314. I bought [this one](http://www.chinalctech.com/index.php?_m=mod_product&_a=view&p_id=900). [This documentation](http://www.turuta.md/DSHEETS/PT2314_3.pdf) says that the minimum power supply is 6V. However I have applied 5V from **Arduino Uno** and it seems to work.

Because I do not have any 6-10V under my hand I just came with the idea that I can attach just 5V to PT2314 and at least to check if the I2C interface is working with your library. The I2C interface worked fine with 5V so I was able to set volume, gain, channel and so on. I was surprised when I've heard the music from the speakers (I've attached RDA5807 tuner and PAM8403 amplifier).

**Comment by andykarpov** [comment]
Ah nice! I'm also notices that this chip works nice with 5V power supply. 
I'm using this chip inside a DAB radio with my own control board. And that manufactured pcb supplied by 5V - so, yes, never trust datasheets :)))

**Comment by wmarkow** [comment]
I think we can close this issue now. We can keep it in mind as a **known issue**.
