### ISSUE TITLE
Pt2314 project with IR remote through Arduino

### ISSUE THREAD

**Issue by tarunesh119** [andykarpov/PT2314#7]
I want this project to operate pt2314 by ir remote

**Comment by wmarkow** [comment]
@tarunesh119, this github project is only an Arduino driver library for **PT2314** device. It is not related to **IR remote**. 

If you want to control PT2314 by infra red then you need to do it by yourself. You need to find some Arduino **IR library** and use it together with **PT2314** library in your project. Of course you need to implement some logic that will react on infra red commands to send a proper commands to **PT2314**.

**Comment by andykarpov** [comment]
Agreed. Closing this issue as invalid
